export default interface detalleOcModelo {
    idOcDetalle? : number, 
	codigo? : string, 
	nombre? : string, 
	descripcion? : string, 
	unidadMedidaC? : string, 
	cantidad? : number, 
	idAdmActivo? : number, 
	fechaAlta? : any, 
	fechaRequerida? : any, 
	justificacion? : string, 
	IdComprasEmpresa? : number, 
	idGenAreaNegocio? : number, 
	idGenCentroCostos? : number, 
	idComprasOC? : number, 
	idAreaTrabajo? : number, 
	cant_encontrada? : number, 
	precio? : number, 
	tasa_iva? : number, 
	subtotal? : number, 
	idProveedor? : number, 
	notas? : string,
	cant_recibido? : number, 
	cant_conforme? : number,
	precio_usd? : number,
	precio_usd_sutotal? : number,
}