export default interface OrdenCompraModelo {
	idComprasOC?: number,
	fechaAlta?: any,
	observaciones?: string,
	idProveedor?: number,
	idAdmActivo?: number,
	IdComprasEmpresa?: number,
	idSolpedCompras?: number,
	monto_total?: number,
	condiciones?: string,
	formas_envio?: string,
	idConfigGerencia?: number,
	idUsuarioAprobo?: number,
	fechaAprobacion?: number,
	monto_total_usd?: number,
	tasa_usd?: number,
	fecha_tasa_usd?: any,
	idEstado?: number,
	estadoActual?: string,
	justificacion? : string,
	correlativo? : string,
}