export default interface solpeddetalleModelo {
    idDetalleSolped? :number, 
	codigo? :string, 
	nombre? :string, 
	descripcion? : string, 
	unidadMedidaC? :any, 
	cantidad? : number, 
	nroActivo? : number, 
	fechaAlta? : any, 
	fechaRequerida? :any, 
	justificacion? :string, 
	IdComprasEmpresa? : number, 
	idGenAreaNegocio? :number, 
	idGenCentroCostos? :number, 
	idSolpedCompras? :number, 
	idAreaTrabajo? : number, 
	cant_encontrada? : number, 
	precio? : number, 
	precio_usd?: number,
	idProveedor? : number, 
	notas? :string,
	cant_recibida? : number,
	tasa_iva?: number,
	precio_iva?: number,
	subtotal?: number,
	precio_usd_sutotal? : number,
	precio_neto? :number,
	precio_neto_usd? :number,
	estado?: any, //{ "proceso": 0, "aprobado": 1, "anulado": 2 }
}