image: node:12

stages:
    - dependencias
    - build
    - containerization
    - deploy

cache:
    paths:
        - node_modules/

install_dependencies:
    stage: dependencias
    script:
        - npm install
        # - npm install -g typescript
    artifacts:
        paths:
            - node_modules/

# DESARROLLO CAMBIA
build:
    stage: build
    script:
        - docker build -t $CI_PROJECT_NAME .
        #- docker image rm my-registry/my-application

register_image:
    stage: containerization
    variables:
        SHA: $CI_COMMIT_SHORT_SHA
    script:
        # - docker tag n_compras $DOCKER_SERVER/n_compras:$SHA
        # - docker tag n_compras $DOCKER_SERVER/n_compras:latest
        # - docker push $DOCKER_SERVER/n_compras:$SHA
        # - docker push $DOCKER_SERVER/n_compras:latest
        - docker tag $CI_PROJECT_NAME $DOCKER_SERVER/$CI_PROJECT_NAME:$SHA
        - docker tag $CI_PROJECT_NAME $DOCKER_SERVER/$CI_PROJECT_NAME:latest
        - docker push $DOCKER_SERVER/$CI_PROJECT_NAME:$SHA
        - docker push $DOCKER_SERVER/$CI_PROJECT_NAME:latest

    only:
        - master
# -------------

deploy_to_desarrollo:
    stage: deploy
    variables:
        MYSQL_SERVER: $DESA_MYSQL_SERVER
        MYSQL_USER: $DESA_MYSQL_USER
        MYSQL_PW: $DESA_MYSQL_PASS
        MYSQL_DB: $DESA_MYSQL_DB
        MYSQL_PORT: $DESA_MYSQL_PORT
        APP_PORT: $APP_PORT
    script:
        - docker-compose down
        - docker-compose up -d --build
        - echo $DESA_MYSQL_SERVER
    only:
        - desarrollo
    tags:
        - desarrollo

deploy_to_prod:
    stage: deploy
    variables:
        MYSQL_SERVER: $PROD_MYSQL_SERVER
        MYSQL_USER: $DESA_MYSQL_USER
        MYSQL_PW: $DESA_MYSQL_PASS
        MYSQL_DB: $DESA_MYSQL_DB
        MYSQL_PORT: $DESA_MYSQL_PORT
        APP_PORT: $APP_PORT
    script:
        #- echo $PROD_MYSQL_SERVER
        - docker pull $DOCKER_SERVER/$CI_PROJECT_NAME:latest
        - docker-compose down
        - docker-compose up -d --build
    only:
        - master
    when: manual
    tags:
        - master
