#Version del docker compose
version: "3.3"

services:
    node-compras:
        image: $DEPLOY_TAG
        container_name: $BUILD_TAG
        restart: always
        ports:   
            - $APP_PORT:$APP_PORT
        networks:
            - webnet            
        environment:
            - MYSQL_SERVER=$MYSQL_SERVER
            - MYSQL_PORT=$MYSQL_PORT
            - MYSQL_DB=$MYSQL_DB
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PW=$MYSQL_PW
            - APP_PORT=$APP_PORT
    
networks:
    webnet:            