#Version del docker compose
version: "3.3"

services:
    node-compras:
        #Contenedor del Frontend de la aplicación, NO ejecuta código de backend
        build: 
            context: .
            #args: 
                #- config=transven
        container_name: node_compras
        restart: always
        #volumes:
            # Los archivos del front deben copiarse en la carpeta /frontend
            #- ./site:/app
            #- ./nginx-custom.conf:/etc/nginx/conf.d/default.conf
        ports:   
            - 8001:8001
        networks:
            - webnet            
        environment:
            - MYSQL_SERVER=45.181.250.100
            - MYSQL_PORT=3306
            - MYSQL_DB=intranets
            - MYSQL_USER=root
            - MYSQL_PW=.4C3r04dm1n
            # si se necesita trabajar con la base de datos local solo cambiar el valor de la variable DEPLOYMENT, no borrarla
            - DEPLOYMENT=dev
            - PORT=8001
        working_dir: /app
        command: bash -c "npm start"
    
networks:
    webnet:            