#Version del docker compose
version: "3.3"

services:
    node-compras:
        image: $DOCKER_SERVER/$CI_PROJECT_NAME:latest

        container_name: $CI_PROJECT_NAME
        restart: always
        ports:   
            - $APP_PORT:$APP_PORT
        networks:
            - webnet            
        environment:
            - MYSQL_SERVER=$MYSQL_SERVER
            - MYSQL_PORT=$MYSQL_PORT
            - MYSQL_DB=$MYSQL_DB
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PW=$MYSQL_PW
            - APP_PORT=$APP_PORT
        working_dir: /app
        command: bash -c "npm start"
        
networks:
    webnet:            